[package]
name = "tray-icon-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
objc = "0.2.7"
tao = "0.24.0"
tray-icon = "0.11.1"
